import Head from "next/head";
import { UserButton, useUser } from "@clerk/nextjs";
import { ReactElement } from "react";
import 'react-multi-carousel/lib/styles.css';
import { FaRecordVinyl } from "react-icons/fa6";
import { GiHamburgerMenu } from "react-icons/gi";
import * as DropdownMenu from '@radix-ui/react-dropdown-menu';
import Link from "next/link";

interface NavProps {
  children: ReactElement;
  searchBar?: ReactElement;
}

export const Nav = ({ children, searchBar }: NavProps) => (
  <>
    <Head>
      <title>Vinyl</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex min-h-screen items-center flex-col bg-slate-950">
    <div className='flex flex-row justify-between p-6 w-full items-end flex-wrap gap-8 bg-slate-900 border-b border-slate-800'>
      <Link href='/'><div className='text-4xl flex flex-row gap-2'>Vinyl <FaRecordVinyl /></div></Link>
      {searchBar && searchBar}
        <div className='order-1 flex flex-row items-center md:order-3 gap-4'>
          <DropdownMenu.Root>
            <DropdownMenu.Trigger asChild>
              <button className="IconButton" aria-label="Customise options">
                <div className='cursor-pointer hover:bg-slate-800 p-2 rounded-md'><GiHamburgerMenu size='24' /></div>
              </button>
            </DropdownMenu.Trigger>
            <DropdownMenu.Portal>
              <DropdownMenu.Content className="cursor-pointer mr-4 bg-slate-100 rounded-lg text-slate-950" sideOffset={5}>
                <DropdownMenu.Item className='hover:bg-slate-300 p-2 rounded-t-lg'>
                  <Link href="/favorites"><div className='text-lg'>Your Ratings</div></Link>
                </DropdownMenu.Item>
                <DropdownMenu.Item className="hover:bg-slate-300 p-2 rounded-b-lg">
                  <div className='text-lg'>Most Popular</div>
                </DropdownMenu.Item>
              </DropdownMenu.Content>
            </DropdownMenu.Portal>
          </DropdownMenu.Root>
          <UserButton afterSignOutUrl='/' />
        </div>
      </div>
      {children}
    </main>
  </>
)