import Head from "next/head";
import { UserButton, useUser } from "@clerk/nextjs";
import { ReactElement } from "react";
import "react-multi-carousel/lib/styles.css";
import { FaRecordVinyl } from "react-icons/fa6";
import { GiHamburgerMenu } from "react-icons/gi";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import Link from "next/link";

interface NavProps {
  children: ReactElement;
  searchBar?: ReactElement;
}

export const Nav = ({ children, searchBar }: NavProps) => (
  <>
    <Head>
      <title>Vinyl</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex min-h-screen flex-col items-center bg-slate-950">
      <div className="flex w-full flex-row flex-wrap items-end justify-between gap-8 border-b border-slate-800 bg-slate-900 p-6">
        <Link href="/">
          <div className="flex flex-row gap-2 text-4xl">
            Vinyl <FaRecordVinyl />
          </div>
        </Link>
        {searchBar && searchBar}
        <div className="order-1 flex flex-row items-center gap-4 md:order-3">
          <DropdownMenu.Root>
            <DropdownMenu.Trigger asChild>
              <button className="IconButton" aria-label="Customise options">
                <div className="cursor-pointer rounded-md p-2 hover:bg-slate-800">
                  <GiHamburgerMenu size="24" />
                </div>
              </button>
            </DropdownMenu.Trigger>
            <DropdownMenu.Portal>
              <DropdownMenu.Content
                className="mr-4 cursor-pointer rounded-lg bg-slate-100 text-slate-950"
                style={{ fontFamily: "sans-serif" }}
                sideOffset={5}
              >
                <DropdownMenu.Item className="rounded-t-lg p-2 hover:bg-slate-300">
                  <Link href="/favorites">
                    <div className="text-lg">Your Ratings</div>
                  </Link>
                </DropdownMenu.Item>
                <DropdownMenu.Item className="rounded-b-lg p-2 hover:bg-slate-300">
                  <div className="text-lg">Most Popular</div>
                </DropdownMenu.Item>
              </DropdownMenu.Content>
            </DropdownMenu.Portal>
          </DropdownMenu.Root>
          <UserButton afterSignOutUrl="/" />
        </div>
      </div>
      {children}
    </main>
  </>
);
